---
- name: Create /etc/systemd/journald.conf.d
  ansible.builtin.file:
    path: '/etc/systemd/journald.conf.d'
    state: 'directory'
    mode: "0750"

- name: Copy retention-time.conf
  ansible.builtin.copy:
    src: 'retention-time.conf'
    dest: '/etc/systemd/journald.conf.d'
    mode: "0640"
  notify:
    - Restart journald
