---
- name: Start dnf-automatic
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    state: started

- name: Enable dnf-automatic
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: true
