---
- name: Start dnf-automatic
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    state: stared

- name: Enable dnf-automatic
  ansible.builtin.systemd:
    name: dnf-automatic.imer
    enabled: true
