---
- name: Install ufw
  ansible.builtin.dnf:
    name: ufw
    state: latest

- name: Start ufw
  ansible.builtin.systemd:
    state: started
    name: ufw

- name: Allow ssh
  community.general.ufw:
    delete: true
    rule: allow
    port: "22"
    proto: tcp

- name: Enable ufw
  community.general.ufw:
    state: enabled
  notify:
    - enable ufw
