---
- name: Deploy role
  hosts: reverse-proxy
  become: true
  roles:
    - dnf
    - timesyncd
    - firewalld
    - sshd
    - fail2ban
    - acme
    - nginx
    - docker
    - ramle_be
    - journald
