---
- name: Test role on vagrant
  hosts: all
  become: true
  roles:
    - firewalld
    - timesyncd
    - dnf
    - sshd
    - acme
    - nginx
    - docker
    - ramle_be
    - fail2ban
    - journald
