---
- name: Create directory
  ansible.builtin.file:
    path: 'ramle.be/'
    state: 'directory'
    mode: 0750
  become: false

- name: Download docker-compose.yml
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/r4iponce/ramle.be/main/docker/docker-compose.yml'
    dest: 'ramle.be/docker-compose.yml'
    mode: 0640
- name: Start docker compose
  ansible.builtin.command: 'docker compose up -d'
  args:
    chdir: "ramle.be"
  become: false
  changed_when: false
