name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache .cache (for ansible-lint)
      id: cache-primes
      uses: actions/cache@v3
      with:
        path: .cache
        key: ${{ runner.os }}-cache
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@main
